### ISSUE TITLE
OnkoDICOM crashes on "Individual Patient Curation" on macOS Monterey 12.5.1 Arm64

### ISSUE THREAD

**Issue by sjswerdloff** [didymo/OnkoDICOM#249]
When I choose "Individual Patient Curation", it crashes. 
The crash has the following message:

PDPI: 127.50000191485792
qt.qpa.fonts: Populating font family aliases took 160 ms. Replace uses of missing font family "Segoe UI" with one that exists to avoid this cost.
Multithreading with maximum 10 threads
<class 'TypeError'> int() argument must be a string, a bytes-like object or a real number, not 'ItemFlag' <traceback object at 0x2a64b1c40>
Traceback (most recent call last):
File "/Users/stuartswerdloff/PythonProjects/OnkoDICOM/src/Controller/TopLevelController.py", line 82, in show_open_patient
self.open_patient_window.check_selected_items()
File "/Users/stuartswerdloff/PythonProjects/OnkoDICOM/src/View/OpenPatientWindow.py", line 429, in check_selected_items
checked_nodes = self.get_checked_nodes(
File "/Users/stuartswerdloff/PythonProjects/OnkoDICOM/src/View/OpenPatientWindow.py", line 578, in get_checked_nodes
recurse(root)
File "/Users/stuartswerdloff/PythonProjects/OnkoDICOM/src/View/OpenPatientWindow.py", line 571, in recurse
if int(child.flags()) & int(Qt.ItemIsUserCheckable) and 
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'ItemFlag'

**Comment by sjswerdloff** [comment]
Changing the code to:

```
if child.flags() & Qt.ItemIsUserCheckable and \
                        child.checkState(0) == Qt.Checked:
```
 fixed it.  Not sure why the bit masks were being converted to int before bitwise &
